# IPL 2026 Full League Stage Schedule
# 70 matches, 28 Mar – 24 May 2026
# Venue names match model's norm_venue() output exactly
# Team names match model's TEAM_SHORT keys exactly

IPL_2026_SCHEDULE = [
    {"match_num": 1,  "date": "2026-03-28", "time": "19:30", "team1": "Royal Challengers Bengaluru", "team2": "Sunrisers Hyderabad",       "venue": "M Chinnaswamy Stadium, Bengaluru"},
    {"match_num": 2,  "date": "2026-03-29", "time": "19:30", "team1": "Mumbai Indians",               "team2": "Kolkata Knight Riders",     "venue": "Wankhede Stadium, Mumbai"},
    {"match_num": 3,  "date": "2026-03-30", "time": "19:30", "team1": "Rajasthan Royals",             "team2": "Chennai Super Kings",       "venue": "Barsapara Cricket Stadium, Guwahati"},
    {"match_num": 4,  "date": "2026-03-31", "time": "19:30", "team1": "Kings XI Punjab",              "team2": "Gujarat Titans",            "venue": "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur"},
    {"match_num": 5,  "date": "2026-04-01", "time": "19:30", "team1": "Lucknow Super Giants",         "team2": "Delhi Capitals",            "venue": "Ekana Stadium, Lucknow"},
    {"match_num": 6,  "date": "2026-04-02", "time": "19:30", "team1": "Kolkata Knight Riders",        "team2": "Sunrisers Hyderabad",       "venue": "Eden Gardens, Kolkata"},
    {"match_num": 7,  "date": "2026-04-03", "time": "19:30", "team1": "Chennai Super Kings",          "team2": "Kings XI Punjab",           "venue": "MA Chidambaram Stadium, Chennai"},
    {"match_num": 8,  "date": "2026-04-04", "time": "15:30", "team1": "Delhi Capitals",               "team2": "Mumbai Indians",            "venue": "Arun Jaitley Stadium, Delhi"},
    {"match_num": 9,  "date": "2026-04-04", "time": "19:30", "team1": "Gujarat Titans",               "team2": "Rajasthan Royals",          "venue": "Narendra Modi Stadium, Ahmedabad"},
    {"match_num": 10, "date": "2026-04-05", "time": "15:30", "team1": "Sunrisers Hyderabad",          "team2": "Lucknow Super Giants",      "venue": "Rajiv Gandhi Intl Stadium, Hyderabad"},
    {"match_num": 11, "date": "2026-04-05", "time": "19:30", "team1": "Royal Challengers Bengaluru", "team2": "Chennai Super Kings",       "venue": "M Chinnaswamy Stadium, Bengaluru"},
    {"match_num": 12, "date": "2026-04-06", "time": "19:30", "team1": "Kolkata Knight Riders",        "team2": "Kings XI Punjab",           "venue": "Eden Gardens, Kolkata"},
    {"match_num": 13, "date": "2026-04-07", "time": "19:30", "team1": "Rajasthan Royals",             "team2": "Mumbai Indians",            "venue": "Barsapara Cricket Stadium, Guwahati"},
    {"match_num": 14, "date": "2026-04-08", "time": "19:30", "team1": "Delhi Capitals",               "team2": "Gujarat Titans",            "venue": "Arun Jaitley Stadium, Delhi"},
    {"match_num": 15, "date": "2026-04-09", "time": "19:30", "team1": "Kolkata Knight Riders",        "team2": "Lucknow Super Giants",      "venue": "Eden Gardens, Kolkata"},
    {"match_num": 16, "date": "2026-04-10", "time": "19:30", "team1": "Rajasthan Royals",             "team2": "Royal Challengers Bengaluru","venue": "Barsapara Cricket Stadium, Guwahati"},
    {"match_num": 17, "date": "2026-04-11", "time": "15:30", "team1": "Kings XI Punjab",              "team2": "Sunrisers Hyderabad",       "venue": "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur"},
    {"match_num": 18, "date": "2026-04-11", "time": "19:30", "team1": "Chennai Super Kings",          "team2": "Delhi Capitals",            "venue": "MA Chidambaram Stadium, Chennai"},
    {"match_num": 19, "date": "2026-04-12", "time": "15:30", "team1": "Lucknow Super Giants",         "team2": "Gujarat Titans",            "venue": "Ekana Stadium, Lucknow"},
    {"match_num": 20, "date": "2026-04-12", "time": "19:30", "team1": "Mumbai Indians",               "team2": "Royal Challengers Bengaluru","venue": "Wankhede Stadium, Mumbai"},
    {"match_num": 21, "date": "2026-04-13", "time": "19:30", "team1": "Sunrisers Hyderabad",          "team2": "Rajasthan Royals",          "venue": "Rajiv Gandhi Intl Stadium, Hyderabad"},
    {"match_num": 22, "date": "2026-04-14", "time": "19:30", "team1": "Chennai Super Kings",          "team2": "Kolkata Knight Riders",     "venue": "MA Chidambaram Stadium, Chennai"},
    {"match_num": 23, "date": "2026-04-15", "time": "19:30", "team1": "Royal Challengers Bengaluru", "team2": "Lucknow Super Giants",      "venue": "M Chinnaswamy Stadium, Bengaluru"},
    {"match_num": 24, "date": "2026-04-16", "time": "19:30", "team1": "Mumbai Indians",               "team2": "Kings XI Punjab",           "venue": "Wankhede Stadium, Mumbai"},
    {"match_num": 25, "date": "2026-04-17", "time": "19:30", "team1": "Gujarat Titans",               "team2": "Kolkata Knight Riders",     "venue": "Narendra Modi Stadium, Ahmedabad"},
    {"match_num": 26, "date": "2026-04-18", "time": "15:30", "team1": "Royal Challengers Bengaluru", "team2": "Delhi Capitals",            "venue": "M Chinnaswamy Stadium, Bengaluru"},
    {"match_num": 27, "date": "2026-04-18", "time": "19:30", "team1": "Sunrisers Hyderabad",          "team2": "Chennai Super Kings",       "venue": "Rajiv Gandhi Intl Stadium, Hyderabad"},
    {"match_num": 28, "date": "2026-04-19", "time": "15:30", "team1": "Kolkata Knight Riders",        "team2": "Rajasthan Royals",          "venue": "Eden Gardens, Kolkata"},
    {"match_num": 29, "date": "2026-04-19", "time": "19:30", "team1": "Kings XI Punjab",              "team2": "Lucknow Super Giants",      "venue": "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur"},
    {"match_num": 30, "date": "2026-04-20", "time": "19:30", "team1": "Gujarat Titans",               "team2": "Mumbai Indians",            "venue": "Narendra Modi Stadium, Ahmedabad"},
    {"match_num": 31, "date": "2026-04-21", "time": "19:30", "team1": "Sunrisers Hyderabad",          "team2": "Delhi Capitals",            "venue": "Rajiv Gandhi Intl Stadium, Hyderabad"},
    {"match_num": 32, "date": "2026-04-22", "time": "19:30", "team1": "Lucknow Super Giants",         "team2": "Rajasthan Royals",          "venue": "Ekana Stadium, Lucknow"},
    {"match_num": 33, "date": "2026-04-23", "time": "19:30", "team1": "Mumbai Indians",               "team2": "Chennai Super Kings",       "venue": "Wankhede Stadium, Mumbai"},
    {"match_num": 34, "date": "2026-04-24", "time": "19:30", "team1": "Royal Challengers Bengaluru", "team2": "Gujarat Titans",            "venue": "M Chinnaswamy Stadium, Bengaluru"},
    {"match_num": 35, "date": "2026-04-25", "time": "15:30", "team1": "Delhi Capitals",               "team2": "Kings XI Punjab",           "venue": "Arun Jaitley Stadium, Delhi"},
    {"match_num": 36, "date": "2026-04-25", "time": "19:30", "team1": "Rajasthan Royals",             "team2": "Sunrisers Hyderabad",       "venue": "Sawai Mansingh Stadium, Jaipur"},
    {"match_num": 37, "date": "2026-04-26", "time": "15:30", "team1": "Gujarat Titans",               "team2": "Chennai Super Kings",       "venue": "Narendra Modi Stadium, Ahmedabad"},
    {"match_num": 38, "date": "2026-04-26", "time": "19:30", "team1": "Lucknow Super Giants",         "team2": "Kolkata Knight Riders",     "venue": "Ekana Stadium, Lucknow"},
    {"match_num": 39, "date": "2026-04-27", "time": "19:30", "team1": "Delhi Capitals",               "team2": "Royal Challengers Bengaluru","venue": "Arun Jaitley Stadium, Delhi"},
    {"match_num": 40, "date": "2026-04-28", "time": "19:30", "team1": "Kings XI Punjab",              "team2": "Rajasthan Royals",          "venue": "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur"},
    {"match_num": 41, "date": "2026-04-29", "time": "19:30", "team1": "Mumbai Indians",               "team2": "Sunrisers Hyderabad",       "venue": "Wankhede Stadium, Mumbai"},
    {"match_num": 42, "date": "2026-04-30", "time": "19:30", "team1": "Gujarat Titans",               "team2": "Royal Challengers Bengaluru","venue": "Narendra Modi Stadium, Ahmedabad"},
    {"match_num": 43, "date": "2026-05-01", "time": "19:30", "team1": "Rajasthan Royals",             "team2": "Delhi Capitals",            "venue": "Sawai Mansingh Stadium, Jaipur"},
    {"match_num": 44, "date": "2026-05-02", "time": "19:30", "team1": "Chennai Super Kings",          "team2": "Mumbai Indians",            "venue": "MA Chidambaram Stadium, Chennai"},
    {"match_num": 45, "date": "2026-05-03", "time": "15:30", "team1": "Sunrisers Hyderabad",          "team2": "Kolkata Knight Riders",     "venue": "Rajiv Gandhi Intl Stadium, Hyderabad"},
    {"match_num": 46, "date": "2026-05-03", "time": "19:30", "team1": "Gujarat Titans",               "team2": "Kings XI Punjab",           "venue": "Narendra Modi Stadium, Ahmedabad"},
    {"match_num": 47, "date": "2026-05-04", "time": "19:30", "team1": "Mumbai Indians",               "team2": "Lucknow Super Giants",      "venue": "Wankhede Stadium, Mumbai"},
    {"match_num": 48, "date": "2026-05-05", "time": "19:30", "team1": "Delhi Capitals",               "team2": "Chennai Super Kings",       "venue": "Arun Jaitley Stadium, Delhi"},
    {"match_num": 49, "date": "2026-05-06", "time": "15:30", "team1": "Sunrisers Hyderabad",          "team2": "Kings XI Punjab",           "venue": "Rajiv Gandhi Intl Stadium, Hyderabad"},
    {"match_num": 50, "date": "2026-05-07", "time": "19:30", "team1": "Lucknow Super Giants",         "team2": "Royal Challengers Bengaluru","venue": "Ekana Stadium, Lucknow"},
    {"match_num": 51, "date": "2026-05-08", "time": "19:30", "team1": "Delhi Capitals",               "team2": "Kolkata Knight Riders",     "venue": "Arun Jaitley Stadium, Delhi"},
    {"match_num": 52, "date": "2026-05-09", "time": "19:30", "team1": "Rajasthan Royals",             "team2": "Gujarat Titans",            "venue": "Sawai Mansingh Stadium, Jaipur"},
    {"match_num": 53, "date": "2026-05-10", "time": "15:30", "team1": "Chennai Super Kings",          "team2": "Lucknow Super Giants",      "venue": "MA Chidambaram Stadium, Chennai"},
    {"match_num": 54, "date": "2026-05-10", "time": "19:30", "team1": "Royal Challengers Bengaluru", "team2": "Mumbai Indians",            "venue": "Shaheed Veer Narayan Singh International Stadium"},
    {"match_num": 55, "date": "2026-05-11", "time": "19:30", "team1": "Kings XI Punjab",              "team2": "Delhi Capitals",            "venue": "HPCA Stadium, Dharamsala"},
    {"match_num": 56, "date": "2026-05-12", "time": "19:30", "team1": "Gujarat Titans",               "team2": "Sunrisers Hyderabad",       "venue": "Narendra Modi Stadium, Ahmedabad"},
    {"match_num": 57, "date": "2026-05-13", "time": "19:30", "team1": "Royal Challengers Bengaluru", "team2": "Kolkata Knight Riders",     "venue": "Shaheed Veer Narayan Singh International Stadium"},
    {"match_num": 58, "date": "2026-05-14", "time": "19:30", "team1": "Kings XI Punjab",              "team2": "Mumbai Indians",            "venue": "HPCA Stadium, Dharamsala"},
    {"match_num": 59, "date": "2026-05-15", "time": "19:30", "team1": "Lucknow Super Giants",         "team2": "Chennai Super Kings",       "venue": "Ekana Stadium, Lucknow"},
    {"match_num": 60, "date": "2026-05-16", "time": "19:30", "team1": "Kolkata Knight Riders",        "team2": "Gujarat Titans",            "venue": "Eden Gardens, Kolkata"},
    {"match_num": 61, "date": "2026-05-17", "time": "15:30", "team1": "Kings XI Punjab",              "team2": "Royal Challengers Bengaluru","venue": "HPCA Stadium, Dharamsala"},
    {"match_num": 62, "date": "2026-05-17", "time": "19:30", "team1": "Delhi Capitals",               "team2": "Rajasthan Royals",          "venue": "Arun Jaitley Stadium, Delhi"},
    {"match_num": 63, "date": "2026-05-18", "time": "19:30", "team1": "Chennai Super Kings",          "team2": "Sunrisers Hyderabad",       "venue": "MA Chidambaram Stadium, Chennai"},
    {"match_num": 64, "date": "2026-05-19", "time": "19:30", "team1": "Rajasthan Royals",             "team2": "Lucknow Super Giants",      "venue": "Sawai Mansingh Stadium, Jaipur"},
    {"match_num": 65, "date": "2026-05-20", "time": "19:30", "team1": "Kolkata Knight Riders",        "team2": "Mumbai Indians",            "venue": "Eden Gardens, Kolkata"},
    {"match_num": 66, "date": "2026-05-21", "time": "19:30", "team1": "Chennai Super Kings",          "team2": "Gujarat Titans",            "venue": "MA Chidambaram Stadium, Chennai"},
    {"match_num": 67, "date": "2026-05-22", "time": "15:30", "team1": "Sunrisers Hyderabad",          "team2": "Royal Challengers Bengaluru","venue": "Rajiv Gandhi Intl Stadium, Hyderabad"},
    {"match_num": 68, "date": "2026-05-23", "time": "19:30", "team1": "Lucknow Super Giants",         "team2": "Kings XI Punjab",           "venue": "Ekana Stadium, Lucknow"},
    {"match_num": 69, "date": "2026-05-24", "time": "15:30", "team1": "Mumbai Indians",               "team2": "Rajasthan Royals",          "venue": "Wankhede Stadium, Mumbai"},
    {"match_num": 70, "date": "2026-05-24", "time": "19:30", "team1": "Kolkata Knight Riders",        "team2": "Delhi Capitals",            "venue": "Eden Gardens, Kolkata"},
]
